from typing import Protocol, List, Any, Optional
from database_types import UserDict, StoreDict

class DatabaseProtocol(Protocol):
    """Protocol describing DB methods used by handlers/bot for static typing.
    Keep minimal; extend as new cross-backend usages appear.
    """
    # User
    def get_user(self, user_id: int) -> Optional[UserDict]: ...
    def add_user(self, user_id: int, username: Optional[str] = None, first_name: Optional[str] = None, role: str = 'customer', city: str | None = None): ...
    def update_user_phone(self, user_id: int, phone: str): ...
    def update_user_city(self, user_id: int, city: str): ...
    def update_user_language(self, user_id: int, language: str): ...
    def get_user_language(self, user_id: int) -> str: ...
    def update_user_role(self, user_id: int, role: str): ...
    def is_admin(self, user_id: int) -> bool: ...

    # Stores / Offers
    def get_user_stores(self, owner_id: int) -> List[StoreDict]: ...
    def get_stores_by_city(self, city: str) -> List[StoreDict]: ...
    def get_active_offers(self, city: str | None = None, store_id: int | None = None) -> List[dict]: ...

    # Favorites
    def get_favorites(self, user_id: int) -> Any: ...
    def add_to_favorites(self, user_id: int, store_id: int): ...
    def remove_from_favorites(self, user_id: int, store_id: int): ...
    def is_favorite(self, user_id: int, store_id: int) -> bool: ...

    # Notifications / toggles
    def toggle_notifications(self, user_id: int) -> bool: ...

    # Admin / misc
    def get_all_admins(self) -> List[int]: ...
    def activate_offer(self, offer_id: int): ...
    def deactivate_offer(self, offer_id: int): ...
    def get_booking_history(self, user_id: int, limit: int = 50) -> Any: ...
    def get_platform_payment_card(self) -> Any: ...
