ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_price INTEGER;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS item_title TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS item_price INTEGER;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS item_original_price INTEGER;
